version: '3'
services:
  db:
    image: postgres
    volumes:
      - ../bvg-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  bvg-graph:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - "./rails/public/assets:/usr/src/app/public/assets"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
