development: &default
  adapter: postgresql
  encoding: unicode
  database: bvggraph_development
  pool: 5
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: bvggraph_test

production:
  <<: *default
  database: bvggraph_production
  username: bvggraph
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
